name: Run Tests

on:
  push:
    branches: [ main ]

jobs:

  api-tests:
    name: API Regression
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          include-prerelease: true

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run API tests (ALL)
        run: bash ./scripts/ci/test-api.sh

      - name: Generate API HTML report
        if: always()
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:**/*.trx -targetdir:report-api -reporttypes:Html

      - name: Upload API TRX results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: '**/TestResults/*.trx'

      - name: Publish API test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: API Tests
          path: '**/TestResults/*.trx'
          reporter: dotnet-trx

      - name: Upload API HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-html-report
          path: report-api

      - name: Upload API traces (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: api-traces
          path: '**/traces/*.zip'


  ui-smoke:
    name: UI Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          include-prerelease: true

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Install Playwright
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          playwright install
          playwright install-deps

      - name: Run UI smoke tests
        run: bash ./scripts/ci/test-ui-smoke.sh

      - name: Generate UI HTML report
        if: always()
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:**/*.trx -targetdir:report-ui -reporttypes:Html

      - name: Upload UI TRX results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: '**/TestResults/*.trx'

      - name: Publish UI test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: UI Smoke Tests
          path: '**/TestResults/*.trx'
          reporter: dotnet-trx

      - name: Upload UI HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-html-report
          path: report-ui

      - name: Upload UI traces (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ui-traces
          path: '**/traces/*.zip'