name: Run Tests

on:
  push:
    branches: [ main ]

jobs:

  api-tests:
    name: API Regression
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          include-prerelease: true

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Install Playwright
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          playwright install
          playwright install-deps

      - name: Run API tests (ALL)
        run: bash ./scripts/ci/test-api.sh

      - name: Upload API results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: '**/TestResults/*.trx'

      - name: Publish API test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: API Tests
          path: '**/TestResults/*.trx'
          reporter: dotnet-trx
      
      - name: Upload Playwright traces
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: api-traces
          path: '**/*.log'


  ui-smoke:
    name: UI Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          include-prerelease: true

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Install Playwright
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          playwright install
          playwright install-deps

      - name: Run UI smoke tests
        run: bash ./scripts/ci/test-ui-smoke.sh

      - name: Upload UI results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: '**/TestResults/*.trx'

      - name: Publish UI test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: UI Smoke Tests
          path: '**/TestResults/*.trx'
          reporter: dotnet-trx

      - name: Upload Playwright traces
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ui-traces
          path: '**/traces/*.zip'